[hookman]

[[hooks]]
name = "Test"
command = "cargo test"
stage = "pre-push"

[[hooks]]
name = "Generate hooks"
command = """
dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/tags.$$"' EXIT INT TERM
ctags --tag-relative=yes -Rf.git/tags.$$ $(git ls-files)
mv $dir/tags.$$ $dir/tags
"""
background = true
stage = "post-commit"
