[hookman]

[[hooks]]
name = "Test"
command = "cargo test"
stage = "pre-push"

[[hooks]]
name = "Generate hooks"
command = "ctags --tag-relative-yes -Rf.git/tags.$$"
background = true
stage = "post-commit"
pass_git_files = true
