[package]
name = "hookman"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5.11"
env_logger = "0.9.0"
eyre = "0.6.5"
log = "0.4.14"
structopt = "0.3.22"
toml = "0.5.8"
