[hookman]

[[hooks]]
name = "Test"
command = "pytest"
stage = "pre-push"

[[hooks]]
name = "Generate hooks"
command = "ctags --tag-relative-yes -Rf.git/tags.$$ $(git ls-files)"
background = true
stage = "post-commit"

[[hooks]]
name = "Lint"
command = "pylint"
# stage defaults to pre-commit
