[hookman]

[[hooks]]
name = "Test"
command = "pytest"
stage = "pre-push"

[[hooks]]
name = "Generate hooks"
command = "ctags --tag-relative-yes -Rf.git/tags.$$"
background = true
stage = "post-commit"
pass_git_files = true

[[hooks]]
name = "Lint"
command = "pylint"
# stage defaults to pre-commit

